name: mchacks13
dependencies:
  - python=3.11.14
  - python-multipart
  - sqlmodel
  - pwdlib
  - pydantic
  - uvicorn
  - pyjwt
  - fastapi
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/mchacks13
